### Criação de um novo usuário
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john@example.com",
  "password": "password123"
}

###

### Criação de um novo produto
POST http://localhost:3000/api/products
Content-Type: application/json

{
  "name": "Laptop",
  "price": 1200,
  "stock": 50
}

###

### Criação de um novo pedido
POST http://localhost:3000/api/orders
Content-Type: application/json

{
  "user": "60d0fe4f5311236168a109ca", 
  "product": "60d0fe4f5311236168a109cb", 
  "quantity": 2,
  "total": 2400,
  "date": "2024-01-01T00:00:00Z"
}
